name: Kiota Gen Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version being released'
        required: true

jobs:
  release:
    name: Release Kiota Gen
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          cd kiota-gen
          npm install
          npm run build

      - name: Set version in package.json
        run: |
          cd kiota-gen/dist
          npm version ${{ github.event.inputs.release-version }}

      - name: Publish to npmjs.com
        run: |
          cd kiota-gen/dist
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ''
